### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by abhilashlr** [poteto/ember-cli-flash#312]
Upgrade ember-cli-flash to 2.0 with the following items:
- [ ] Remove initializer that injects `flashMessages` service. This will be a breaking change for apps since the apps would require to write their own initializer that will inject the service or follow dependency injection by doing:
  ```
  flashMessages: inject.service()
  ```

- [ ] Should 2.x support Ember 1.x and 2.x versions also?
- [ ] Drop jQuery
- [ ] Porting to typescript

Feel free to add more to this list of items.

**Comment by makepanic** [comment]
Porting the addon to typescript (via [ember-cli-typescript](https://github.com/typed-ember/ember-cli-typescript)) or adding type definitions would also be awesome.

With many options for adding flash messages, it's really helpful to get correct types for each field.

**Comment by HerveSeger** [comment]
I just upgraded my application to ember `v3.14.2` and I can see the following deprecation:

https://deprecations.emberjs.com/v3.x#toc_action-mouseenter-leave-move

So it should probably be added to the list.

**Comment by st-h** [comment]
@HerveSeger This should already be fixed in `1.8.0`: https://github.com/poteto/ember-cli-flash/pull/304 However it seems that it hasn't been released yet.

**Comment by stukalin** [comment]
@abhilashlr close this perhaps? This addon is on 2.1.2 already with some of your suggestions in place.
